### ISSUE TITLE
Constructed URLs always use custom url configuration instead of relative paths 

### ISSUE THREAD

**Issue by Loriden** [saschawildgrube/servicenow-devtools#104]
Hi Sascha, 

Realise this might be an edge case - but i have a problem that is impacting uptake of this application. 

I'm working within instances where there are multiple URLs configurated, based on the IdP you authenticate with this. It seems like all the URLs configured for the manual, application and various other pages use the first custom URL in the custom URL table. This causes multi-sso configurations (and even local accounts) that utilise the links to be redirected to login again and potentially destroy their access token, due to the high-security plugin being enabled. 

Any chance we can use relative paths or retrieve the current url being accessed instead? I had a go at pulling apart the DevTools Application page but didn't get there in a reasonable amount of time.

**Comment by saschawildgrube** [comment]
That is indeed an edge case.
Let's catch up via mail: sascha.wildgrube@servicenow.com

**Comment by Loriden** [comment]
Got to the root cause on this one - culprit was the '_glide.servlet.uri_' property being updated by enforcing a custom URL to be the instance url, via the 'Set Instance URL' checkbox.  This property is retrieved by a variety of Script Includes utilised by DevTools. 

This issue was surfaced by a convergence of SSO configuration mandating a SAML token & the use of internal accounts for administration along with the high security plugin killing sessions when the URL changes, so that the instance URL changed for administrators but not end users. 

Solution we've chosen to pursue is using a DevTools extension point to utilise a different URI for DevTools links as opposed to the '_glide.servlet.uri_' property.
